# Generated by Django 4.2 on 2024-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermsCondition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='last_Updated',
            field=models.DateField(auto_now=True),
        ),
    ]
