# Generated by Django 4.2 on 2024-06-02 10:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TermsCondition', '0002_alter_termsandcondition_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandcondition',
            name='acknowledgment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
