# Generated by Django 4.2 on 2024-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TermsCondition', '0003_alter_termsandcondition_acknowledgment'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
