# Generated by Django 4.2 on 2024-06-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image_1', models.ImageField(upload_to='news/')),
                ('image_2', models.ImageField(upload_to='news/')),
                ('image_3', models.ImageField(upload_to='news/')),
            ],
        ),
    ]
