# Generated by Django 4.2 on 2024-06-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
