# Generated by Django 4.2 on 2024-05-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='heroSection/')),
            ],
        ),
    ]
