# Generated by Django 4.2 on 2024-05-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyQuestioned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HowToCardWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('icon', models.FileField(upload_to='icon/')),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('card_setup_video', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
