# Generated by Django 4.2 on 2024-05-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0002_frequentlyquestioned_howtocardwork_orderstep_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyQuestioned',
            new_name='FrequentlyQuestion',
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='google_map_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
