# Generated by Django 4.2 on 2024-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0003_rename_frequentlyquestioned_frequentlyquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image_1', models.ImageField(upload_to='products/')),
                ('image_2', models.ImageField(null=True, upload_to='products/')),
                ('image_3', models.ImageField(null=True, upload_to='products/')),
                ('is_black_material', models.BooleanField(default=False)),
                ('is_white_material', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
            ],
        ),
    ]
