# Generated by Django 4.2 on 2024-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
