# Generated by Django 4.2 on 2024-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0006_package_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_up', models.BooleanField(default=True)),
                ('is_down', models.BooleanField(default=False)),
            ],
        ),
    ]
